### ISSUE TITLE
A random unprofessional question

### ISSUE THREAD

**Issue by Ra0k** [oszika05/bin-finder-android#1]
Hey, 

I just came along this super interesting, open-source initial of yours. I am wondering if you can help me fix my printer. 

Thank you in advance!

Yours forever,
Ra0k

**Comment by oszika05** [comment]
Hello my friend!

Have you tried plugging it in?

Yours forever,
Razul

**Comment by Ra0k** [comment]
Ah, thanks! I will call you if I need you again! :'D
